# Generated by Django 2.2 on 2021-07-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField(max_length=5)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
