# Generated by Django 2.2 on 2021-07-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_app', '0005_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold',
            field=models.ManyToManyField(related_name='user_sold_item', to='solo_app.User'),
        ),
    ]
