# Generated by Django 2.2 on 2021-07-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_app', '0007_auto_20210723_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
