# Generated by Django 2.2 on 2021-07-26 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solo_app', '0008_auto_20210723_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=455)),
                ('avatar_Main_Img', models.ImageField(upload_to='../static/img/')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whos_avatar', to='solo_app.User')),
            ],
        ),
    ]
